# Project 2: Travel & Hospitality – Dynamic Pricing using Reinforcement Learning (RL)

# Week 3: DQN Hyperparameter Tuning

**Objective:** Optimize the Deep Q-Network (DQN) agent by experimenting with different hyperparameter configurations such as learning rate, batch size, discount factor (gamma), epsilon decay, and target network update frequency. Analyze the impact of each configuration on training performance and identify the best-performing model based on average reward and convergence.

**Prepared by:** Vishnupriyan  
**Internship:** Infotact Solutions & Co.  
**Week:** 3

---

## Hyperparameters Evaluated

- Learning Rate
- Batch Size
- Discount Factor (Gamma)
- Epsilon Decay
- Target Update Frequency

---

## Performance Metrics

- Average Reward
- Training Loss
- Training Time
- Best Hyperparameter Configuration

---

## Expected Outcome

The best hyperparameter configuration will be selected based on the highest average reward and stable training performance. These optimized parameters will be used in Week 4 for policy evaluation and performance visualization.

In [13]:
import itertools
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
hyperparameter_config = {
    "learning_rate": [0.001, 0.0005, 0.0001],
    "batch_size": [32, 64],
    "gamma": [0.95, 0.99],
    "epsilon_decay": [0.995, 0.999],
    "target_update": [10, 20]
}

hyperparameter_config

{'learning_rate': [0.001, 0.0005, 0.0001],
 'batch_size': [32, 64],
 'gamma': [0.95, 0.99],
 'epsilon_decay': [0.995, 0.999],
 'target_update': [10, 20]}

In [15]:
keys = hyperparameter_config.keys()

values = hyperparameter_config.values()

experiments = list(itertools.product(*values))

print("Total Experiments :", len(experiments))

experiments[:5]

Total Experiments : 48

[(0.001, 32, 0.95, 0.995, 10),
 (0.001, 32, 0.95, 0.995, 20),
 (0.001, 32, 0.95, 0.999, 10),
 (0.001, 32, 0.95, 0.999, 20),
 (0.001, 32, 0.99, 0.995, 10)]

In [16]:
df = pd.DataFrame(
    experiments,
    columns=keys
)

df.head()

   learning_rate  batch_size  gamma  epsilon_decay  target_update
0          0.001          32   0.95          0.995             10
1          0.001          32   0.95          0.995             20
2          0.001          32   0.95          0.999             10
3          0.001          32   0.95          0.999             20
4          0.001          32   0.99          0.995             10

In [17]:
df["Average Reward"] = None
df["Loss"] = None
df["Training Time"] = None

df.head()

,learning_rate,batch_size,gamma,epsilon_decay,target_update,Average Reward,Loss,Training Time
0,0.001,32,0.95,0.995,10,None,None,None
1,0.001,32,0.95,0.995,20,None,None,None
2,0.001,32,0.95,0.999,10,None,None,None
3,0.001,32,0.95,0.999,20,None,None,None
4,0.001,32,0.99,0.995,10,None,None,None

In [18]:
df.to_csv(
    "hyperparameter_experiments.csv",
    index=False
)

print("Experiment sheet created successfully.")

Experiment sheet created successfully.

In [19]:
def plot_results(df):

    if df["Average Reward"].isnull().all():

        print("No results available.")

        return

    plt.figure(figsize=(10,5))

    plt.plot(df["Average Reward"])

    plt.xlabel("Experiment")

    plt.ylabel("Average Reward")

    plt.title("Hyperparameter Comparison")

    plt.grid(True)

    plt.show()

    plot_results(df)

In [20]:
def best_configuration(df):

    if df["Average Reward"].isnull().all():

        print("Training results not available.")

        return

    best = df.loc[df["Average Reward"].idxmax()]

    print(best)